
FAIL at (core_test.clj:34)
    Expected: 3
      Actual: 4
^^^^ The previous failure was expected ^^^^

FAIL at (core_test.clj:45)
Actual result did not agree with the checking function.
        Actual result: 4
    Checking function: odd?
^^^^ The previous failure was expected ^^^^

FAIL at (core_test.clj:80)
Actual result did not agree with the checking function.
        Actual result: [3 3 1 2]
    Checking function: (just [1 2 3] :in-any-order)
    The checker said this about the reason:
        Expected three elements. There were four.
^^^^ The previous failure was expected ^^^^

FAIL at (core_test.clj:130)        
These calls were not made the right number of times:
    (alive? ...cell...) [expected at least once, actually never called]

FAIL at (core_test.clj:131)        
These calls were not made the right number of times:
    (neighbor-count ...cell...) [expected at least once, actually never called]

FAIL at (core_test.clj:128)
Actual result did not agree with the checking function.
        Actual result: nil
    Checking function: truthy
^^^^ The previous three failures were expected ^^^^

FAIL at (core_test.clj:231)        
These calls were not made the right number of times:
    (property-of ...data-structure-value-1...) [expected at least once, actually never called]

FAIL at (core_test.clj:231)        
These calls were not made the right number of times:
    (data-structure) [expected at least once, actually never called]
^^^^ The previous two failures were expected ^^^^

Testing basic.core-test

Ran 0 tests containing 0 assertions.
0 failures, 0 errors.
{:type :summary, :pass 0, :test 0, :error 0, :fail 0}
